// Generated by CoffeeScript 1.9.2
(function() {
  MyApp.module("entities", function(Entities, MyApp) {
    return Entities.alertPublic = function(message) {
      return alert(message);
    };
  });

}).call(this);
